export const metadata = {
  title: "Frontend Mentor | Entertainment web app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#10141e]">
        <div className="flex min-h-screen w-screen flex-col items-start justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
