import NavBar from "@/components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Frontend Mentor | Entertainment web app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#10141e]">
        <div className="flex min-h-screen w-screen flex-col items-start lg:flex-row  lg:p-8">
          <div className="w-screen  lg:w-[7%]">
            <NavBar />
          </div>
          <div className="w-screen px-4 pt-6 md:px-6  lg:w-[93%] lg:pt-0 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
